---
- name: playbook_1
  hosts: all
  vars:
   a: "my first task"
   b: "my second task"
  tasks:
   -  name: task_1
      debug:
        msg: "{{a}}"
   -  name: task_2
      debug:
       msg: "{{b}}"
...
